/**
 * 계산기 페이지 Shadow DOM 패널 CSS — F7 로 calcFill.js 의 인라인 문자열에서 분리.
 * globalThis.nuoCalcPanelCss 로 export. manifest content_scripts 에 calcFill.js 보다 먼저 로드.
 *
 * 본 라운드(계산기 자동입력 — 팀 슬롯 원클릭): 옛 좌/우 puck(좌측 공격 / 우측 수비) UI 를
 * 폐기하고, 팀빌더 FAB(우하단 단일 진입점, 7칸 슬롯 + 큰 토글) 외관을 차용. 단,
 * 팀빌더 FAB 의 하늘색 테마와 구분하기 위해 `.is-mode-atk` (yellowish) / `.is-mode-def`
 * (greenish) 두 모드의 색 토큰을 CSS 변수로 두고, 토글 상태에 따라 동적으로 전환한다.
 *
 * 슬롯 hover 아이콘도 동일 변수로 검(공격) / 방패(수비) 한 쪽만 표시.
 */
(function (g) {
  'use strict';
  g.nuoCalcPanelCss = [
    ':host { all: initial; }',
    '* { box-sizing: border-box; font-family: system-ui, "Malgun Gothic", "Apple SD Gothic Neo", sans-serif; }',
    /* mode 전환 시 그라데이션 cross-fade — @property/<image> interpolation 이 Shadow DOM */
    /* 에서 안 잡히는 케이스가 있어, 확실한 길로 가짜 요소(::before atk / ::after def) */
    /* 두 층을 깔고 opacity 만 토글. 아래 .fab-btn:not(:disabled)::before/::after 참조. (#2) */
    /* ===== 모드 토큰 (yellowish 공격 / greenish 수비) — 토글 클래스로 cascade ===== */
    /* atk/def 아이콘은 같은 자리에 absolute 로 깔고 opacity 변수(1/0)로 보이기/숨기기 — */
    /* display:block/none 으로 토글하면 (a) display 는 transition 이 안 먹어 mode 전환이 */
    /* 순간 swap 으로 보임 (#4) (b) flex 부모가 잃어 SVG 가 좌상단에 박힘(#1) — 두 문제 동시 해결. */
    /* atk = amber 톤, def = emerald 톤. 팀빌더 FAB 가 색=하늘색 / 아이콘=`#2a6f8f` 으로 */
    /* “테마와 묶인 어두운 색” 패턴을 쓰는 것을 그대로 차용 — 각 모드의 그라데이션과 묶여 보이는 */
    /* 진한 톤. (사용자 #1) */
    '.fab-root {',
    '  --nuo-cf-glow-1: rgba(245, 158, 11, 0.18);',
    '  --nuo-cf-glow-2: rgba(245, 158, 11, 0.24);',
    '  --nuo-cf-glow-3: rgba(245, 158, 11, 0.20);',
    '  --nuo-cf-color: #92400e;',     /* atk 아이콘·텍스트 — 배경 그라데이션과 분리해 진한 톤 유지 */
    '  --nuo-cf-accent: #b45309;',
    '  --nuo-cf-vis-atk: 1;',
    '  --nuo-cf-vis-def: 0;',
    '}',
    '.fab-root.is-mode-def {',
    '  --nuo-cf-glow-1: rgba(16, 185, 129, 0.14);',
    '  --nuo-cf-glow-2: rgba(16, 185, 129, 0.19);',
    '  --nuo-cf-glow-3: rgba(16, 185, 129, 0.15);',
    '  --nuo-cf-color: #065f46;',     /* def 아이콘·텍스트 — 배경과 분리해 진한 톤 유지 */
    '  --nuo-cf-accent: #065f46;',
    '  --nuo-cf-vis-atk: 0;',
    '  --nuo-cf-vis-def: 1;',
    '}',
    /* ===== keyframes ===== */
    '@keyframes nuo-cf-glow {',
    '  0%, 100% { box-shadow: 0 4px 14px var(--nuo-cf-glow-1), 0 0 0 1px var(--nuo-cf-glow-2); }',
    '  50% { box-shadow: 0 6px 18px var(--nuo-cf-glow-3), 0 0 0 1px var(--nuo-cf-glow-2); }',
    '}',
    '@keyframes nuo-cf-bounce {',
    '  0% { transform: scale(0.96); }',
    '  60% { transform: scale(1.04); }',
    '  100% { transform: scale(1); }',
    '}',
    '@keyframes nuo-cf-spin { to { transform: rotate(360deg); } }',
    /* 아래 5개는 팀빌더 FAB 의 fab-fb-busy-out / fab-fb-spin-ic / fab-fb-done-layer / */
    /* fab-fb-check-pop / fab-err-shake-btn 와 동일 동작. 사용자 “팀빌더 fab 그대로 베껴줘” (#2). */
    '@keyframes nuo-cf-busy-out { from { opacity: 1; } to { opacity: 0; } }',
    '@keyframes nuo-cf-spin-ic { from { transform: scale(1); opacity: 1; } to { transform: scale(0.32); opacity: 0; } }',
    '@keyframes nuo-cf-done-layer { from { opacity: 0; } to { opacity: 1; } }',
    '@keyframes nuo-cf-check-pop { from { transform: scale(0.28); opacity: 0; } to { transform: scale(1); opacity: 1; } }',
    '@keyframes nuo-cf-err-shake {',
    '  0%, 100% { transform: translateX(0); }',
    '  9% { transform: translateX(-9px); }',
    '  21% { transform: translateX(8px); }',
    '  33% { transform: translateX(-4.5px); }',
    '  45% { transform: translateX(3.5px); }',
    '  57% { transform: translateX(-2px); }',
    '  69% { transform: translateX(1.2px); }',
    '  81% { transform: translateX(-0.55px); }',
    '  91% { transform: translateX(0.25px); }',
    '}',
    /* ===== layout (팀빌더 FAB 와 동일 위치·크기) ===== */
    '.fab-root {',
    '  position: fixed; z-index: 2147483645; right: clamp(24px, 5vw, 48px); bottom: clamp(24px, 5vw, 48px);',
    '  display: flex; flex-direction: column; align-items: flex-end; gap: 8px;',
    '}',
    '.fab-root.nuo-off { opacity: 0; pointer-events: none; visibility: hidden; }',
    '.fab-inner { display: flex; flex-direction: column; align-items: flex-end; gap: 8px; }',
    '.fab-dock { position: relative; display: inline-block; vertical-align: bottom; }',
    '.fab-dock-main { position: relative; width: 80px; display: flex; flex-direction: column; align-items: center; }',
    '.fab-party-col { position: relative; width: 80px; min-height: 80px; display: flex; flex-direction: column; align-items: center; justify-content: flex-end; }',
    '.fab-party-wrap { position: relative; display: flex; flex-direction: column; align-items: center; width: 80px; }',
    '.fab-slot-row { position: relative; width: 80px; height: 62px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; overflow: visible; }',
    '.fab-slots {',
    '  position: absolute; left: 0; right: 0; bottom: calc(100% + 8px); z-index: 1;',
    '  display: flex; flex-direction: column; align-items: center; gap: 8px; width: 80px; overflow: visible;',
    '  opacity: 0; visibility: hidden; pointer-events: none;',
    '  transition: opacity 0.09s ease, visibility 0.09s;',
    '}',
    '.fab-dock--open .fab-slots { opacity: 1; visibility: visible; pointer-events: auto; }',
    /* ===== .fab-btn 베이스 ===== */
    /* isolation: isolate — 가짜 요소의 z-index:-1 이 부모 stacking context 까지 새지 않게 가둠. */
    '.fab-btn {',
    '  position: relative; isolation: isolate;',
    '  border: none; cursor: pointer; display: inline-flex; align-items: center;',
    '  justify-content: center; flex-shrink: 0; border-radius: 50%; color: var(--nuo-cf-color);',
    '}',
    /* 가짜 요소 두 층: ::before = atk(노란), ::after = def(초록). opacity 변수만 토글하면 cross-fade. */
    /* var() 가 가리키는 그라데이션 값을 직접 transition 하는 건 Shadow DOM 환경에서 불안정해서 폐기. */
    '.fab-btn:not(:disabled)::before,',
    '.fab-btn:not(:disabled)::after {',
    '  content: ""; position: absolute; left: 0; top: 0; right: 0; bottom: 0;',
    '  border-radius: inherit; z-index: -1; pointer-events: none;',
    '  transition: opacity 0.18s ease;',
    '}',
    '.fab-btn:not(:disabled)::before {',
    '  background-image: linear-gradient(155deg, #fffefb 0%, #fef3c7 42%, #fcd34d 100%);',
    '  opacity: var(--nuo-cf-vis-atk);',
    '}',
    '.fab-btn:not(:disabled)::after {',
    '  background-image: linear-gradient(155deg, #f5fffa 0%, #d1fae5 44%, #6ee7b7 100%);',
    '  opacity: var(--nuo-cf-vis-def);',
    '}',
    '.fab-btn:not(:disabled) {',
    /* 배경은 ::before/::after 가 담당. 여기엔 background-image 없음. */
    '  animation: nuo-cf-glow 3.4s ease-in-out -0.6s infinite;',
    '  transition: transform 0.22s ease, filter 0.2s ease, opacity 0.2s ease, color 0.18s ease;',
    '}',
    '.fab-btn:not(:disabled):not(.fab-busy):not(.fab-done):not(.fab-err):hover {',
    '  transform: scale(1.06); filter: brightness(1.02) saturate(1.03);',
    '}',
    '.fab-btn:not(:disabled):not(.fab-busy):not(.fab-done):not(.fab-err):active,',
    '.fab-btn.fab-press:not(:disabled):not(.fab-busy):not(.fab-done):not(.fab-err) {',
    '  transform: scale(0.92); filter: brightness(0.98) saturate(0.98);',
    '  transition: none !important;',
    '}',
    '.fab-btn:disabled {',
    '  cursor: not-allowed; opacity: 0.72; filter: saturate(0.45) brightness(0.96);',
    '  animation: none;',
    '  background-image: linear-gradient(155deg, #f8fafc 0%, #e2e8f0 55%, #cbd5e1 100%);',
    '  color: #64748b;',
    '  box-shadow: 0 4px 14px rgba(15, 23, 42, 0.08), 0 0 0 1px rgba(148, 163, 184, 0.35);',
    '}',
    '.fab-btn.fab-bounce { animation: nuo-cf-glow 3.4s ease-in-out -0.6s infinite, nuo-cf-bounce 0.18s cubic-bezier(0.22, 1, 0.36, 1) !important; }',
    /* ===== .fab-mode-toggle (큰 버튼 — 검·방패 SVG) ===== */
    /* 두 아이콘을 같은 자리에 absolute 로 깔고 opacity 변수로 cross-fade. flex 부모가 그대로 남아 */
    /* SVG 가 정중앙에 위치(#1) + opacity transition 으로 mode 전환 부드러움(#4). */
    '.fab-mode-toggle { width: 80px; height: 80px; border-radius: 50%; }',
    '.fab-toggle-ic {',
    '  position: absolute; left: 0; top: 0; right: 0; bottom: 0;',
    '  display: flex; align-items: center; justify-content: center;',
    '  pointer-events: none;',
    '  opacity: 0;',
    '  color: var(--nuo-cf-color);',
    '  transition: opacity 0.18s ease, color 0.18s ease;',
    '}',
    /* svg 는 currentColor 상속 — 부모의 color transition 을 함께 받음. */
    '.fab-toggle-ic svg { width: 36px; height: 36px; }',
    '.fab-toggle-ic-atk { opacity: var(--nuo-cf-vis-atk); }',
    '.fab-toggle-ic-def { opacity: var(--nuo-cf-vis-def); }',
    /* ===== .fab-slot (일반 슬롯) ===== */
    '.fab-slot { width: 62px; height: 62px; border-radius: 50%; font-size: 16px; font-weight: 700; overflow: hidden; }',
    '.fab-slot-label { display: flex; align-items: center; justify-content: center; width: 100%; height: 100%; }',
    '.fab-slot-mon {',
    '  position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%);',
    '  max-width: 82%; max-height: 82%; width: auto; height: auto;',
    '  object-fit: contain; display: none; pointer-events: none;',
    '}',
    '.fab-slot.has-mon .fab-slot-mon { display: block; }',
    '.fab-slot.has-mon .fab-slot-fallback-num { display: none; }',
    '.fab-slot-fallback-num { pointer-events: none; }',
    /* 빈 슬롯 — disabled 안 걸어 hover/click 이 살아있되, 시각적으론 회색·dim 으로. */
    /* (팀빌더 FAB 의 .fab-slot--empty 동일 톤 — 옛 .fab-btn:disabled 스타일을 .is-empty 로 옮김.) */
    '.fab-slot.is-empty {',
    '  cursor: pointer;',
    '  animation: none !important;',
    '  opacity: 0.72; filter: saturate(0.45) brightness(0.96);',
    '  color: #64748b;',
    '  background-image: linear-gradient(155deg, #f8fafc 0%, #e2e8f0 55%, #cbd5e1 100%);',
    '  box-shadow: 0 4px 14px rgba(15, 23, 42, 0.08), 0 0 0 1px rgba(148, 163, 184, 0.35);',
    '}',
    /* 빈 슬롯의 mode 그라데이션 가짜 요소는 숨김 — 회색 직배경이 보이도록. */
    '.fab-slot.is-empty::before, .fab-slot.is-empty::after { opacity: 0 !important; }',
    /* (옛 .fab-slot-write 인-슬롯 위치 CSS 는 Write 가 좌측 puck 으로 이전되며 폐기) */
    /* ===== hover/busy/done/err feedback — 팀빌더 FAB 의 fab-btn-feedback 패턴 그대로 베낌 ===== */
    /* 핵심: hover/done bg 는 “밝은 반투명 화이트”(rgba(255,255,255,0.5x)), 아이콘은 진한 색. */
    /* busy/err bg 는 “어두운 반투명”(rgba(15,23,42,0.28)), 아이콘은 슬레이트/레드. */
    '.fab-fb { position: absolute; left: 0; top: 0; right: 0; bottom: 0; border-radius: inherit; pointer-events: none; overflow: hidden; }',
    '.fab-fb > .lyr {',
    '  position: absolute; left: 0; top: 0; right: 0; bottom: 0;',
    '  display: flex; align-items: center; justify-content: center;',
    '  border-radius: inherit; opacity: 0;',
    '}',
    '.fab-fb .lyr-bg { position: absolute; left: 0; top: 0; right: 0; bottom: 0; border-radius: inherit; }',
    /* 단일 아이콘 layer (busy/done/err): 일반적인 중앙 정렬 */
    '.fab-fb .lyr-busy .lyr-ic, .fab-fb .lyr-done .lyr-ic, .fab-fb .lyr-err .lyr-ic {',
    '  position: relative; z-index: 1;',
    '  display: flex; align-items: center; justify-content: center;',
    '  width: 100%; height: 100%;',
    '}',
    '.fab-fb .lyr-busy .lyr-ic svg, .fab-fb .lyr-done .lyr-ic svg, .fab-fb .lyr-err .lyr-ic svg {',
    '  width: 46%; height: 46%; max-width: 38px; max-height: 38px; flex-shrink: 0;',
    '}',
    /* hover (검/방패/ban 세 아이콘 layered) — atk·def 는 mode 따라, 빈 슬롯이면 ban */
    '.fab-fb .lyr-hover .lyr-bg { background: rgba(255, 255, 255, 0.52); }',
    '.fab-fb .lyr-hover .lyr-ic {',
    '  position: absolute; left: 0; top: 0; right: 0; bottom: 0;',
    '  display: flex; align-items: center; justify-content: center;',
    '  color: var(--nuo-cf-color);',
    '  opacity: 0;',
    '  transition: opacity 0.18s ease, color 0.18s ease;',
    '}',
    '.fab-fb .lyr-hover .lyr-ic svg { width: 46%; height: 46%; max-width: 38px; max-height: 38px; flex-shrink: 0; }',
    /* 채워진 슬롯: 단일 file-import 아이콘 (mode 색은 .lyr-ic 의 color: var(--nuo-cf-color) 로 자동 tint). */
    '.fab-fb .lyr-hover .lyr-ic-import { opacity: 1; }',
    /* 빈 슬롯: import 안 보이고 ban (슬레이트 톤 - 팀빌더 #a8b3c4) 만. */
    '.fab-slot.is-empty .fab-fb .lyr-hover .lyr-ic-import { opacity: 0 !important; }',
    '.fab-slot.is-empty .fab-fb .lyr-hover .lyr-ic-ban { opacity: 1; color: #a8b3c4; }',
    '.fab-slot.is-empty .fab-fb .lyr-hover .lyr-ic-ban svg { width: 105%; height: 105%; max-width: none; max-height: none; }',
    /* hover 발화 — busy/done/err 진행 중에는 안 뜸. */
    '.fab-btn:not(:disabled):not(.fab-busy):not(.fab-done):not(.fab-err):hover .fab-fb .lyr-hover {',
    '  opacity: 1; transition: opacity 0.14s ease;',
    '}',
    /* busy: 어두운 반투명 + 슬레이트 spinner */
    '.fab-fb .lyr-busy .lyr-bg { background: rgba(15, 23, 42, 0.28); }',
    '.fab-fb .lyr-busy .lyr-ic { color: #475569; }',
    '.fab-btn.fab-busy .fab-fb .lyr-busy { opacity: 1; transition: opacity 0.12s ease; }',
    '.fab-btn.fab-busy .fab-fb .lyr-busy .lyr-ic svg { animation: nuo-cf-spin 1.1s linear infinite; transform-origin: 50% 50%; }',
    '.fab-btn.fab-busy { cursor: progress; pointer-events: none; }',
    /* done: 밝은 반투명 + 초록 체크. busy → done 천이 시 spin-ic 가 축소 사라지고 check 가 pop. */
    '.fab-fb .lyr-done .lyr-bg { background: rgba(255, 255, 255, 0.5); }',
    '.fab-fb .lyr-done .lyr-ic { color: #16a34a; }',
    '.fab-btn.fab-done .fab-fb .lyr-busy { animation: nuo-cf-busy-out 0.26s ease forwards; }',
    '.fab-btn.fab-done .fab-fb .lyr-busy .lyr-ic { animation: nuo-cf-spin-ic 0.28s ease forwards; }',
    '.fab-btn.fab-done .fab-fb .lyr-done { animation: nuo-cf-done-layer 0.32s ease 0.1s forwards; }',
    '.fab-btn.fab-done .fab-fb .lyr-done .lyr-ic { animation: nuo-cf-check-pop 0.44s cubic-bezier(0.34, 1.45, 0.64, 1) 0.14s both; }',
    '.fab-btn.fab-done { pointer-events: none; }',
    /* err: 어두운 반투명 + 빨간 ban + 버튼 자체 흔들림. */
    '.fab-fb .lyr-err .lyr-bg { background: rgba(15, 23, 42, 0.28); }',
    '.fab-fb .lyr-err .lyr-ic { color: #dc2626; }',
    '.fab-btn.fab-err { animation: nuo-cf-err-shake 0.42s cubic-bezier(0.32, 0.72, 0.27, 1) forwards; pointer-events: none; }',
    '.fab-btn.fab-err .fab-fb .lyr-err { opacity: 1; transition: opacity 0.1s ease; }',
    '.fab-btn.fab-err .fab-fb .lyr-hover, .fab-btn.fab-err .fab-fb .lyr-busy, .fab-btn.fab-err .fab-fb .lyr-done { opacity: 0 !important; }',
    /* ===== Write 단일 morph — 팀빌더 FAB .fab-settings-morph 패턴 그대로 (#3) ===== */
    /* puck 과 panel 이 별도 엘리먼트가 아니라 한 엘리먼트가 hover 시 자기 자신을 패널로 변형. */
    /* 사이즈도 팀빌더와 동일 52×52 → 확장 시 280×168~240. border-radius 도 26 → 14 로 부드럽게. */
    '.fab-write-wrap {',
    '  position: absolute; right: calc(100% + 12px); bottom: 0; z-index: 4;',
    '  display: flex; align-items: flex-end;',
    '  opacity: 0; visibility: hidden; pointer-events: none;',
    '  transition: opacity 0.18s ease, visibility 0.18s;',
    '}',
    '.fab-dock--open .fab-write-wrap { opacity: 1; visibility: visible; pointer-events: auto; }',
    /* morph 자체 — 기본 52px circle, hover 시 280×168 rounded rect 로 확장. */
    /* 팀빌더 fab-settings-morph 의 transition 곡선·duration 그대로. */
    '.fab-write-morph {',
    '  position: relative; isolation: isolate;',
    '  width: 52px; min-height: 52px; max-height: 52px; border-radius: 26px;',
    '  overflow: hidden;',
    '  color: var(--nuo-cf-color);',
    '  animation: nuo-cf-glow 3.4s ease-in-out -0.6s infinite;',
    '  cursor: pointer;',
    '  transition: width 0.22s ease, min-height 0.24s ease, max-height 0.24s ease, border-radius 0.2s ease,',
    '    box-shadow 0.35s ease, filter 0.2s ease, transform 0.22s ease, color 0.18s ease;',
    '}',
    /* atk/def 그라데이션은 기존 가짜 요소 두 층 패턴 그대로 — opacity 변수만 토글. */
    '.fab-write-morph::before, .fab-write-morph::after {',
    '  content: ""; position: absolute; left: 0; top: 0; right: 0; bottom: 0;',
    '  border-radius: inherit; z-index: -1; pointer-events: none;',
    '  transition: opacity 0.18s ease;',
    '}',
    '.fab-write-morph::before {',
    '  background-image: linear-gradient(155deg, #fffefb 0%, #fef3c7 42%, #fcd34d 100%);',
    '  opacity: var(--nuo-cf-vis-atk);',
    '}',
    '.fab-write-morph::after {',
    '  background-image: linear-gradient(155deg, #f5fffa 0%, #d1fae5 44%, #6ee7b7 100%);',
    '  opacity: var(--nuo-cf-vis-def);',
    '}',
    /* hover/focus-within 확장 — 팀빌더 fab-settings-morph 와 같은 모양 변화. */
    '.fab-write-wrap:hover .fab-write-morph,',
    '.fab-write-wrap:focus-within .fab-write-morph {',
    '  cursor: default;',
    '  width: 280px; min-height: 168px; max-height: 240px; border-radius: 14px;',
    '  animation: none;',
    '  box-shadow: 0 12px 40px rgba(15, 23, 42, 0.16), 0 0 0 1px rgba(15, 23, 42, 0.08);',
    '}',
    /* 확장 시 뜨는 “밝은” 배경 — 팀빌더처럼 그라데이션 위로 layered. mode-neutral 로 단순화. */
    '.fab-write-bg-expanded {',
    '  position: absolute; left: 0; top: 0; right: 0; bottom: 0;',
    '  border-radius: inherit;',
    '  background-image: linear-gradient(180deg, #fafaf9 0%, #ffffff 42%, #f5f5f4 100%);',
    '  opacity: 0; pointer-events: none;',
    '  z-index: 0;',
    '  transition: opacity 0.22s ease;',
    '}',
    '.fab-write-wrap:hover .fab-write-bg-expanded,',
    '.fab-write-wrap:focus-within .fab-write-bg-expanded { opacity: 1; }',
    /* gear (펜 아이콘 — 팀빌더 .fab-settings-gear 와 같이 absolute, hover 시 opacity 0). */
    '.fab-write-gear {',
    '  position: absolute; left: 0; top: 0; right: 0; bottom: 0;',
    '  display: flex; align-items: center; justify-content: center;',
    '  pointer-events: none;',
    '  z-index: 1;',
    '  color: var(--nuo-cf-color);',
    '  transition: opacity 0.12s ease, color 0.18s ease;',
    '}',
    '.fab-write-wrap:hover .fab-write-gear,',
    '.fab-write-wrap:focus-within .fab-write-gear { opacity: 0; }',
    '.fab-write-gear svg { width: 22px; height: 22px; }',
    /* panel content — morph 확장 후에 fade in. width 280 고정 (overflow hidden 으로 작은 모드에선 클립). */
    '.fab-write-panel-content {',
    '  position: relative; z-index: 2;',
    '  width: 280px; padding: 12px;',
    '  display: flex; flex-direction: column; gap: 8px;',
    '  opacity: 0; pointer-events: none;',
    '  transition: opacity 0.22s ease 0.06s;',
    '}',
    '.fab-write-wrap:hover .fab-write-panel-content,',
    '.fab-write-wrap:focus-within .fab-write-panel-content {',
    '  opacity: 1; pointer-events: auto;',
    '}',
    '.fab-write-morph:focus-visible { outline: 2px solid rgba(15, 23, 42, 0.4); outline-offset: 3px; }',
    '.fab-write-head {',
    '  display: flex; align-items: center; justify-content: flex-start;',
    '  font-size: 13px; font-weight: 600; color: var(--nuo-cf-accent);',
    '  transition: color 0.18s ease;',
    '}',
    '.fab-write-inp {',
    '  width: 100%; padding: 8px 10px; font-size: 13px;',
    '  border: 1px solid rgba(15, 23, 42, 0.18); border-radius: 10px;',
    '  background: #f8fafc; color: #0f172a; outline: none;',
    '}',
    '.fab-write-inp:focus { border-color: var(--nuo-cf-accent); background: #ffffff; }',
    /* Write apply 버튼 — 같은 가짜 요소 두 층 패턴으로 cross-fade. */
    '.fab-write-apply {',
    '  position: relative; isolation: isolate;',
    '  display: inline-flex; align-items: center; justify-content: center; gap: 6px;',
    '  padding: 8px 12px; border-radius: 10px; border: none; cursor: pointer;',
    '  color: var(--nuo-cf-color);',
    '  font-size: 13px; font-weight: 600;',
    '  transition: filter 0.15s ease, transform 0.15s ease, color 0.18s ease;',
    '}',
    '.fab-write-apply::before, .fab-write-apply::after {',
    '  content: ""; position: absolute; left: 0; top: 0; right: 0; bottom: 0;',
    '  border-radius: inherit; z-index: -1; pointer-events: none;',
    '  transition: opacity 0.18s ease;',
    '}',
    '.fab-write-apply::before {',
    '  background-image: linear-gradient(155deg, #fffefb 0%, #fef3c7 42%, #fcd34d 100%);',
    '  opacity: var(--nuo-cf-vis-atk);',
    '}',
    '.fab-write-apply::after {',
    '  background-image: linear-gradient(155deg, #f5fffa 0%, #d1fae5 44%, #6ee7b7 100%);',
    '  opacity: var(--nuo-cf-vis-def);',
    '}',
    '.fab-write-apply:hover { filter: brightness(1.04) saturate(1.05); }',
    '.fab-write-apply:active { transform: scale(0.97); }',
    '.fab-write-apply[aria-busy="true"] { opacity: 0.7; cursor: wait; }',
    '.fab-write-spinner {',
    '  width: 12px; height: 12px; border: 2px solid rgba(15, 23, 42, 0.25); border-top-color: #0f172a;',
    '  border-radius: 50%; animation: nuo-cf-spin 0.9s linear infinite;',
    '}',
    '.fab-write-status {',
    '  margin: 0; font-size: 12px; line-height: 1.4; color: #475569; min-height: 1em;',
    '  word-break: keep-all;',
    '}',
    '.fab-write-status.err { color: #b91c1c; }',
    '.fab-write-status.ok { color: #065f46; }',
    /* ===== 메뉴 헤더 토스트(슬롯 데이터 없을 때) ===== */
    '.fab-head-toast {',
    '  position: absolute; left: auto; right: calc(100% + 12px); top: 0; z-index: 5;',
    '  max-width: 240px; padding: 8px 10px; font-size: 12px; line-height: 1.35;',
    '  color: #991b1b; background: #fff1f2; border: 1px solid #fecaca;',
    '  border-radius: 10px; word-break: keep-all; box-shadow: 0 8px 24px rgba(15, 23, 42, 0.12);',
    '  opacity: 0; visibility: hidden; pointer-events: none;',
    '  transition: opacity 0.16s ease, visibility 0.16s;',
    '}',
    '.fab-dock--open .fab-head-toast.show { opacity: 1; visibility: visible; }',
    ''
  ].join('\n');
})(typeof globalThis !== 'undefined' ? globalThis : self);
