/**
 * 간단 스피드 계산기 Shadow DOM 패널 CSS — F7 로 speedOutspeedCalc.js 의 인라인 문자열에서 분리.
 * globalThis.nuoSpeedPanelCss 로 export. manifest content_scripts 에 speedOutspeedCalc.js 보다 먼저 로드.
 *
 * 일부 셀렉터(`.v-input__*`, `.v-label`, `.v-text-field__slot`)는 스마트누오 Vuetify 입력 필드를
 * 시각적으로 모방하기 위한 것 — `mountPanelInto` 의 prosset HTML 구조와 짝.
 */
(function (g) {
  'use strict';
  g.nuoSpeedPanelCss = [
    ':host { all: initial; }',
    '* {',
    '  -webkit-text-size-adjust: 100%;',
    '  word-break: normal; tab-size: 4;',
    '  text-rendering: optimizeLegibility;',
    '  -webkit-font-smoothing: antialiased;',
    '  -webkit-tap-highlight-color: rgba(0,0,0,0);',
    '  font-family: SCDream, sans-serif;',
    '  box-sizing: border-box;',
    '}',
    '@keyframes nuo-speed-host-in {',
    '  from { opacity: 0; transform: translateX(-8px); }',
    '  to { opacity: 1; transform: translateX(0); }',
    '}',
    '.wrap {',
    '  display: block;',
    '  animation: nuo-speed-host-in .32s cubic-bezier(.25,.8,.5,1) both;',
    '}',
    '.panel-shell {',
    '  transition: max-width .32s cubic-bezier(.25,.8,.5,1);',
    '}',
    '.wrap.collapsed .panel-shell { max-width: 0; }',
    '.panel {',
    '  position: relative;',
    '  background: #fff; border: 1px solid #d9d9d9; border-radius: 12px;',
    '  box-shadow: 0 8px 24px rgba(15, 23, 42, 0.12);',
    '  padding: 12px 10px 14px; color: #0f172a; width: 189px;',
    '  flex-shrink: 0;',
    '  transition: opacity .26s cubic-bezier(.25,.8,.5,1), transform .32s cubic-bezier(.25,.8,.5,1);',
    '}',
    '.wrap.collapsed .panel {',
    '  opacity: 0;',
    '  transform: translateX(-10px);',
    '  pointer-events: none;',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  .wrap { animation: none; }',
    '  .panel-shell { transition: none; }',
    '  .panel { transition: none; }',
    '  .wrap.collapsed .panel { transform: none; }',
    '}',
    '.chev {',
    '  position: absolute; top: 60px; left: -10px;',
    '  width: 22px; height: 22px;',
    '  border: 1px solid #d9d9d9;',
    '  background: #fff;',
    '  color: #626262; font-size: 10px; line-height: 1;',
    '  cursor: pointer; padding: 0;',
    '  border-radius: 50%;',
    '  font-family: SCDream, sans-serif;',
    '  display: flex; align-items: center; justify-content: center;',
    '  box-shadow: 0 2px 6px rgba(15, 23, 42, 0.08);',
    '  transition: color .3s cubic-bezier(.25,.8,.5,1);',
    '}',
    '.chev:hover { color: #e4007f; }',
    '.chev::before {',
    '  content: "◀";',
    '  display: inline-block;',
    '  text-indent: -0.1em;',
    '  transition: transform .3s cubic-bezier(.25,.8,.5,1);',
    '}',
    '.wrap.collapsed .chev::before { transform: rotate(-180deg); }',
    '.topRow {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  gap: 8px; margin-bottom: 14px;',
    '}',
    '.tg-group { display: flex; gap: 4px; flex: 0 0 auto; }',
    '.toggle {',
    '  flex: 0 0 auto;',
    '  height: 20px; padding: 0 7px;',
    '  border-radius: 10px;',
    '  border: 1px solid rgb(233, 196, 106);',
    '  background: rgb(233, 196, 106); color: #fff;',
    '  font-family: SCDream, sans-serif;',
    '  font-size: 10px; line-height: 1;',
    '  letter-spacing: -0.3px;',
    '  cursor: pointer; user-select: none;',
    '  transition: background .15s, color .15s, border-color .15s;',
    '}',
    '.toggle.on {',
    '  background: #e4007f;',
    '  border-color: #e4007f;',
    '  color: #fff;',
    '}',
    '.toggle.opp {',
    '  position: absolute;',
    '  right: 10px; top: 105px;',
    '  height: 18px; padding: 0 6px;',
    '  border-radius: 9px;',
    '  font-size: 9px;',
    '}',
    '.cur {',
    '  flex: 0 0 auto;',
    '  font-size: 12px; color: #0f172a;',
    '  letter-spacing: -0.3px;',
    '}',
    '.cur b { font-weight: 700; color: #e4007f; }',
    '.preset-boxes-wrap { position: relative; width: 100%; }',
    '.preset-boxes-wrap.speed-pop-click .preset { cursor: pointer; }',
    '.preset-boxes-wrap.speed-pop-click .v-input-input {',
    '  pointer-events: none;',
    '}',
    '.boxes { display: flex; gap: 6px; }',
    '.preset { flex: 0 0 52px; width: 52px; min-width: 0; position: relative; }',
    '.species-pop {',
    '  position: absolute; left: 0; right: 0; top: calc(100% + 6px); z-index: 25;',
    '  background: #fff; border: 1px solid #d9d9d9; border-radius: 8px;',
    '  box-shadow: 0 8px 20px rgba(15, 23, 42, 0.14); padding: 8px 10px;',
    '  font-size: 10px; color: #0f172a; letter-spacing: -0.25px;',
    '  overflow: visible; pointer-events: auto;',
    '}',
    '.species-pop-tail {',
    '  position: absolute; top: -9px; left: 0; width: 18px; height: 9px;',
    '  transform: translateX(-50%); pointer-events: none; z-index: 2;',
    '}',
    '.species-pop-tail::before {',
    '  content: ""; position: absolute; left: 50%; bottom: 0;',
    '  transform: translateX(-50%); width: 0; height: 0;',
    '  border-left: 9px solid transparent; border-right: 9px solid transparent;',
    '  border-bottom: 9px solid #d9d9d9;',
    '}',
    '.species-pop-tail::after {',
    '  content: ""; position: absolute; left: 50%; bottom: -1px;',
    '  transform: translateX(-50%); width: 0; height: 0;',
    '  border-left: 8px solid transparent; border-right: 8px solid transparent;',
    '  border-bottom: 8px solid #fff;',
    '}',
    '.species-pop[hidden] { display: none !important; }',
    '.species-pop-title {',
    '  font-weight: 700; font-size: 9px; color: #636363; margin-bottom: 8px; line-height: 1.35;',
    '}',
    '.species-pop-body {',
    '  max-height: min(96vh, 3600px); overflow-y: auto;',
    '}',
    '.species-pop-row { margin-bottom: 6px; }',
    '.species-pop-row:last-child { margin-bottom: 0; }',
    '.species-pop-tier {',
    '  font-weight: 700; display: inline; margin-right: 4px;',
    '}',
    '.species-pop-names {',
    '  display: inline; word-break: keep-all;',
    '}',
    '.species-pop-row.hi .species-pop-tier { color: #e4007f; }',
    '.species-pop-row.hi .species-pop-names { color: #0f172a; }',
    '.species-pop-row.muted .species-pop-tier,',
    '.species-pop-row.muted .species-pop-names { color: #94a3b8; }',
    '.species-pop-divider {',
    '  display: flex; align-items: center; gap: 8px;',
    '  margin: 6px 0;',
    '}',
    '.species-pop-divider-line {',
    '  flex: 1; min-width: 0; height: 1px; background: #cbd5e1;',
    '}',
    '.species-pop-divider-label {',
    '  flex: 0 0 auto; font-size: 9px; font-weight: 700;',
    '  color: #64748b; letter-spacing: -0.2px; padding: 0 6px; background: #fff;',
    '}',
    '.species-pop-divider--outspeed .species-pop-divider-label {',
    '  color: #d6689a;',
    '}',
    '.species-pop-row.tie .species-pop-tier,',
    '.species-pop-row.tie .species-pop-names { color: #0f172a; }',
    '.v-input__control {',
    '  line-height: 1.5; font-size: 16px; letter-spacing: normal;',
    '  text-align: left;',
    '  background-repeat: no-repeat;',
    '  padding: 0; margin: 0;',
    '  display: flex; flex-direction: column;',
    '  height: auto; flex-grow: 1; flex-wrap: wrap;',
    '  min-width: 0; width: 100%;',
    '  border-radius: inherit; color: currentColor;',
    '}',
    '.v-input__slot {',
    '  line-height: 1.5; font-size: 16px; letter-spacing: normal;',
    '  text-align: left; color: currentColor;',
    '  margin: 0;',
    '  display: flex; position: relative;',
    '  transition: .3s cubic-bezier(.25,.8,.5,1);',
    '  transition-property: height, min-height;',
    '  width: 100%;',
    '  border-radius: 8px;',
    '  cursor: text; align-items: stretch;',
    '  background: transparent;',
    '  margin-bottom: 0;',
    '  height: 50px; min-height: 40px;',
    '  padding: 0 12px;',
    '}',
    '.v-input__slot > fieldset {',
    '  line-height: 1.5; font-size: 16px; letter-spacing: normal;',
    '  text-align: left; cursor: text;',
    '  background-repeat: no-repeat;',
    '  padding: 0; margin: 0;',
    '  border: 1px solid;',
    '  border-color: #d8d8d8 !important;',
    '  border-radius: 8px;',
    '  border-collapse: collapse;',
    '  border-style: solid; border-width: 1px;',
    '  bottom: 0; left: 0;',
    '  pointer-events: none;',
    '  position: absolute;',
    '  right: 0; top: -5px;',
    '  transition-duration: .15s;',
    '  transition-property: color;',
    '  transition-timing-function: cubic-bezier(.25,.8,.25,1);',
    '  color: rgba(0,0,0,.26);',
    '}',
    '.v-input__slot > fieldset > legend {',
    '  font-size: 16px; letter-spacing: normal;',
    '  cursor: text; border-collapse: collapse;',
    '  pointer-events: none;',
    '  background-repeat: no-repeat;',
    '  margin: 0;',
    '  border: 0; color: inherit;',
    '  display: table;',
    '  white-space: normal;',
    '  max-width: 100%;',
    '  line-height: 11px;',
    '  padding: 0;',
    '  margin: 0 auto;',
    '  transition: width .3s cubic-bezier(.25,.8,.5,1);',
    '  text-align: center !important;',
    '  width: 28px;',
    '}',
    '.v-input__slot > fieldset > legend > span {',
    '  font-size: 16px; letter-spacing: normal;',
    '  cursor: text; border-collapse: collapse;',
    '  pointer-events: none;',
    '  color: inherit; white-space: normal;',
    '  line-height: 11px; text-align: center !important;',
    '  background-repeat: no-repeat;',
    '  padding: 0; margin: 0;',
    '}',
    '.v-text-field__slot {',
    '  line-height: 1.5; font-size: 16px; letter-spacing: normal;',
    '  text-align: left; color: currentColor; cursor: text;',
    '  background-repeat: no-repeat;',
    '  padding: 0; margin: 0;',
    '  align-items: center;',
    '  display: flex;',
    '  flex: 1 1 auto;',
    '  position: relative;',
    '}',
    '.v-label {',
    '  text-align: left;',
    '  margin: 0;',
    '  min-height: 8px;',
    '  transition: .3s cubic-bezier(.25,.8,.5,1);',
    '  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
    '  max-width: 133%;',
    '  pointer-events: auto;',
    '  height: 20px; letter-spacing: normal;',
    '  transform-origin: top left;',
    '  top: 10px; left: 50% !important; right: auto;',
    '  display: flex; justify-content: center;',
    '  color: #888 !important;',
    '  font-size: 9px !important;',
    '  line-height: 20px !important;',
    '  transform: translateY(-18px) translateX(-50%);',
    '  padding: 0 4px;',
    '  background: #fff;',
    '  position: absolute;',
    '}',
    '.v-input-input {',
    '  background-repeat: no-repeat;',
    '  margin: 0;',
    '  border-radius: 0;',
    '  font: inherit;',
    '  background-color: transparent;',
    '  border-style: none;',
    '  cursor: default;',
    '  flex: 1 1 auto;',
    '  line-height: 20px;',
    '  padding: 8px 0 8px;',
    '  max-width: 100%; min-width: 0; width: 100%;',
    '  max-height: 32px;',
    '  text-align: center;',
    '  color: #626262 !important;',
    '  font-size: 14px !important;',
    '}',
    '.v-input-input:focus { outline: none; }',
    '.caption {',
    '  font-size: 10px; color: #636363; text-align: center;',
    '  margin-top: 10px; letter-spacing: -0.3px;',
    '}',
  ].join('\n');
})(typeof globalThis !== 'undefined' ? globalThis : self);
